version: '3'
services:
  app:
    image: first-go-project:latest
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db
    entrypoint: /app/entrypoint.sh  # Specify the entry point script
    environment:
      TWILIO_AUTH_TOKEN: 66cd4e3b178108f486e8a558aa4d49cf
      TWILIO_ACCOUNT_SID: AC729653ba85434ab1e60023fb3d38d604
  db:
    image: mysql:5.7.43
    environment:
      MYSQL_ROOT_PASSWORD: daddy
      MYSQL_DATABASE: food-db
    ports:
      - "3306:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: